version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: .
    image: immensusf/yamdb_final:lastest
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - static_value:/code/static/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web

volumes:
  postgres_data:
  static_value: